In [2]:
import jax
import jax.numpy as jnp

In [3]:
aa = jnp.array([1., 2, 3])

In [4]:
aa

Array([1., 2., 3.], dtype=float32)

In [5]:
aa[:2]

Array([1., 2.], dtype=float32)

In [11]:
jnp.sum(aa)

Array(6., dtype=float32)

In [13]:
jnp.zeros([1])

Array([0.], dtype=float32)